### Users
GET http://localhost:3000/users/1

### Users
POST http://localhost:3000/users
content-type: application/json

{
  "email": "a@gmail.co",
  "password": "123456"
}

### DELETE Users
DELETE http://localhost:3000/users/1

### UPDATE Users
PATCH http://localhost:3000/users/1
content-type: application/json

{
  "email": "ag@gmails.com",
  "password": "123456s",
  "firstName": "Prateek",
  "lastName": "Anand",
  "phone": [],
  "countryId": 41
}

### Login users
POST http://localhost:3000/users/login
content-type: application/json

{
  "email": "ag@gmails.com",
  "password": "123456s"
}

### WhoAmI
GET http://localhost:3000/users/whoami

### Logout users
POST http://localhost:3000/users/logout